<li class="o-chat--wrapper" {{#commentId}}id="commentid-{{commentId}}"{{/commentId}} data-timestamp="{{timestamp}}">
	<span class="o-chat--timestamp">
		<time class="{{#relativeTime}}o-date{{/relativeTime}}" datetime="{{datetime}}">
			{{dateToShow}}&nbsp;
		</time>
	</span>

	<div class="o-chat--author">
		{{author.displayName}}:
	</div>

	<div class="o-chat--content">
		{{{content}}}
	</div>

	{{#adminMode}}
		<a href="#" class="o-chat--delete">Delete</a>
	{{/adminMode}}
	
	<div class="o-comment-ui--clear"></div>
</li>
